name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      
      - name: Generate
        run: ./gtfs_realtime/generate.sh

      - name: Go mod tidy check
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: Build
        run: go build -o build/ -v ./...

      - name: Test
        run: go test -v ./...
